### ISSUE TITLE
Desktop version crash

### ISSUE THREAD

**Issue by slartus** [AlexGladkov/Odyssey#21]
example project: https://github.com/slartus/Moca/tree/sample/odyssey-desktop-bug

java.lang.NoSuchFieldError: end
	at org.jetbrains.skia.impl.Library._nAfterLoad(Native Method)
	at org.jetbrains.skia.impl.Library$Companion._nAfterLoad(Library.jvm.kt)
	at org.jetbrains.skiko.Library.load(Library.kt:66)
	at org.jetbrains.skiko.SkiaLayer.<clinit>(SkiaLayer.jvm.kt:29)
	at androidx.compose.ui.awt.ComposeLayer.<init>(ComposeLayer.desktop.kt:73)
	at androidx.compose.ui.awt.ComposePanel.addNotify(ComposePanel.desktop.kt:111)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4791)
	at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:733)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/java.awt.Window.addNotify(Window.java:787)
	at java.desktop/java.awt.Frame.addNotify(Frame.java:490)
	at java.desktop/java.awt.Window.show(Window.java:1049)
	at java.desktop/java.awt.Component.show(Component.java:1732)
	at java.desktop/java.awt.Component.setVisible(Component.java:1679)
	at java.desktop/java.awt.Window.setVisible(Window.java:1032)
	at SetupKt.setupNavigation(setup.kt:34)

**Comment by slartus** [comment]
fixed with
compose 1.0.0
and kotlin  1.6.10
